# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 272c848a24dbc263a20139008a69ce73f5aea87249d0a86b8dc054e96e3854d1d344692bf2336d2c9e87aa3a46108f50c5698018a39d7b9ac557f0008d3917a6

test:
  secret_key_base: cc4a2328ff68ebbdd06f066e3bef8b958688514a172c098863dd25a1ce354de41992de4bf53da7ba6dfbcb47f948e338303d5652a814ab84a3fb70a32f90a126

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
